import os
import httpx
from dotenv import load_dotenv

load_dotenv()

SUPABASE_URL = os.getenv('SUPABASE_URL', 'https://rykfqebqdvunwxqkheex.supabase.co').rstrip('/')
SUPABASE_KEY = os.getenv('SUPABASE_KEY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5a2ZxZWJxZHZ1bnd4cWtoZWV4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4ODIyOTg1OSwiZXhwIjoyMTAzODA1ODU5fQ.NCpBUHYAUSME_EjCeo6hyNGv4LkpLg9B6XCqY4LkYBM')
SUPABASE_PAT = os.getenv('SUPABASE_PAT', 'sbp_ee207100cbe762916e60181d68fc47f452633ab2')
PROJECT_REF = 'rykfqebqdvunwxqkheex'

client = httpx.Client(timeout=60.0)

def run_migration():
    print('[*] Migrating Supabase schema for B2B Client Orders, Wholesale Pricing and Matrix Exports...')
    
    ddl_sql = """
    -- 1. Extend products table with B2B commercial fields
    ALTER TABLE public.products
    ADD COLUMN IF NOT EXISTS wholesale_price NUMERIC(10,2) DEFAULT 14.50,
    ADD COLUMN IF NOT EXISTS retail_price NUMERIC(10,2) DEFAULT 26.00,
    ADD COLUMN IF NOT EXISTS cost_price NUMERIC(10,2) DEFAULT 8.50,
    ADD COLUMN IF NOT EXISTS moq INTEGER DEFAULT 3,
    ADD COLUMN IF NOT EXISTS stock_quantity INTEGER DEFAULT 120,
    ADD COLUMN IF NOT EXISTS is_b2b_active BOOLEAN DEFAULT TRUE;

    -- 2. B2B Clients Table
    CREATE TABLE IF NOT EXISTS public.b2b_clients (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_name TEXT NOT NULL,
        tax_id TEXT,
        contact_name TEXT,
        email TEXT,
        phone TEXT,
        address TEXT,
        city TEXT,
        country TEXT DEFAULT 'Argentina',
        price_tier TEXT DEFAULT 'MAYORISTA_ESTANDAR',
        discount_rate NUMERIC(5,2) DEFAULT 0,
        notes TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
    );

    CREATE INDEX IF NOT EXISTS idx_b2b_clients_company ON public.b2b_clients(company_name);
    CREATE INDEX IF NOT EXISTS idx_b2b_clients_tax_id ON public.b2b_clients(tax_id);

    -- 3. B2B Orders Table
    CREATE TABLE IF NOT EXISTS public.b2b_orders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_number TEXT UNIQUE NOT NULL,
        client_id BIGINT REFERENCES public.b2b_clients(id) ON DELETE SET NULL,
        client_name TEXT NOT NULL,
        client_tax_id TEXT,
        client_email TEXT,
        client_phone TEXT,
        status TEXT DEFAULT 'DRAFT',
        currency TEXT DEFAULT 'USD',
        subtotal NUMERIC(12,2) DEFAULT 0,
        discount_amount NUMERIC(12,2) DEFAULT 0,
        tax_amount NUMERIC(12,2) DEFAULT 0,
        shipping_amount NUMERIC(12,2) DEFAULT 0,
        total_amount NUMERIC(12,2) DEFAULT 0,
        payment_terms TEXT DEFAULT 'Transferencia Bancaria Anticipada',
        validity_days INTEGER DEFAULT 15,
        notes TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
    );

    CREATE INDEX IF NOT EXISTS idx_b2b_orders_number ON public.b2b_orders(order_number);
    CREATE INDEX IF NOT EXISTS idx_b2b_orders_status ON public.b2b_orders(status);
    CREATE INDEX IF NOT EXISTS idx_b2b_orders_client_id ON public.b2b_orders(client_id);

    -- 4. B2B Order Items Table
    CREATE TABLE IF NOT EXISTS public.b2b_order_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id BIGINT REFERENCES public.b2b_orders(id) ON DELETE CASCADE,
        product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
        sku TEXT,
        ean TEXT,
        product_name TEXT NOT NULL,
        brand_name TEXT,
        quantity INTEGER NOT NULL DEFAULT 1,
        unit_price NUMERIC(10,2) NOT NULL DEFAULT 0,
        discount_percent NUMERIC(5,2) DEFAULT 0,
        subtotal NUMERIC(10,2) NOT NULL DEFAULT 0
    );

    CREATE INDEX IF NOT EXISTS idx_b2b_order_items_order ON public.b2b_order_items(order_id);
    CREATE INDEX IF NOT EXISTS idx_b2b_order_items_product ON public.b2b_order_items(product_id);

    -- Enable RLS and add public access policies
    ALTER TABLE public.b2b_clients ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Public all access on b2b_clients" ON public.b2b_clients;
    CREATE POLICY "Public all access on b2b_clients" ON public.b2b_clients FOR ALL USING (true) WITH CHECK (true);

    ALTER TABLE public.b2b_orders ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Public all access on b2b_orders" ON public.b2b_orders;
    CREATE POLICY "Public all access on b2b_orders" ON public.b2b_orders FOR ALL USING (true) WITH CHECK (true);

    ALTER TABLE public.b2b_order_items ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Public all access on b2b_order_items" ON public.b2b_order_items;
    CREATE POLICY "Public all access on b2b_order_items" ON public.b2b_order_items FOR ALL USING (true) WITH CHECK (true);
    """

    res = client.post(
        f'https://api.supabase.com/v1/projects/{PROJECT_REF}/database/query',
        headers={'Authorization': f'Bearer {SUPABASE_PAT}'},
        json={'query': ddl_sql}
    )
    
    if res.status_code in (200, 201):
        print('[✓] Supabase schema migration completed successfully!')
    else:
        print(f'[!] Migration failed {res.status_code}: {res.text}')
        return False

    # Seed Sample B2B Clients if empty
    headers = {
        'apikey': SUPABASE_KEY,
        'Authorization': f'Bearer {SUPABASE_KEY}',
        'Content-Type': 'application/json',
        'Prefer': 'return=representation'
    }

    check_res = client.get(f'{SUPABASE_URL}/rest/v1/b2b_clients?select=id&limit=1', headers=headers)
    if check_res.status_code == 200 and len(check_res.json()) == 0:
        print('[*] Seeding default B2B clients...')
        sample_clients = [
            {
                'company_name': 'K-Glow Beauty Concept Store',
                'tax_id': '30-71829304-8',
                'contact_name': 'Mariana Rossi',
                'email': 'compras@kglow.com.ar',
                'phone': '+54 11 4892-3321',
                'address': 'Av. Santa Fe 1842',
                'city': 'Buenos Aires',
                'country': 'Argentina',
                'price_tier': 'MAYORISTA_PREMIUM',
                'discount_rate': 5.0,
                'notes': 'Cliente VIP, local boutique en Recoleta.'
            },
            {
                'company_name': 'Dermocosmética del Valle S.A.',
                'tax_id': '30-65489123-4',
                'contact_name': 'Dr. Lucas Benítez',
                'email': 'pedidos@dermovalle.com',
                'phone': '+54 261 422-9080',
                'address': 'San Martín 1045',
                'city': 'Mendoza',
                'country': 'Argentina',
                'price_tier': 'DISTRIBUIDOR_REGIONAL',
                'discount_rate': 10.0,
                'notes': 'Distribuidor oficial para Cuyo, pedidos mensuales.'
            },
            {
                'company_name': 'Skin Lab Córdoba',
                'tax_id': '27-33928172-3',
                'contact_name': 'Camila Funes',
                'email': 'camila@skinlabcba.com',
                'phone': '+54 351 567-1122',
                'address': 'Belgrano 450',
                'city': 'Córdoba',
                'country': 'Argentina',
                'price_tier': 'MAYORISTA_ESTANDAR',
                'discount_rate': 0.0,
                'notes': 'Cadena de 3 locales de cosmética coreana.'
            },
            {
                'company_name': 'Farmacias San Gabriel Retail',
                'tax_id': '30-58493012-9',
                'contact_name': 'Rodrigo Albarracín',
                'email': 'abastecimiento@sangabriel.com.ar',
                'phone': '+54 341 445-9800',
                'address': 'Bv. Oroño 890',
                'city': 'Rosario',
                'country': 'Argentina',
                'price_tier': 'DISTRIBUIDOR_REGIONAL',
                'discount_rate': 12.0,
                'notes': 'Cadena farmacéutica con góndola K-Beauty.'
            }
        ]
        seed_res = client.post(f'{SUPABASE_URL}/rest/v1/b2b_clients', headers=headers, json=sample_clients)
        print(f'[✓] Seeded {len(sample_clients)} B2B clients: {seed_res.status_code}')

    return True

if __name__ == '__main__':
    run_migration()
