import os
import sys
import httpx
from dotenv import load_dotenv

sys.path.append(r'C:\Users\Camilo Ortiz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages')
import bcrypt

load_dotenv()

SUPABASE_URL = os.getenv('SUPABASE_URL', 'https://rykfqebqdvunwxqkheex.supabase.co').rstrip('/')
SUPABASE_KEY = os.getenv('SUPABASE_KEY', '')
SUPABASE_PAT = os.getenv('SUPABASE_PAT', '')
PROJECT_REF = os.getenv('SUPABASE_PROJECT_REF', 'rykfqebqdvunwxqkheex')

client = httpx.Client(timeout=30.0)

def hash_pw(pw: str) -> str:
    return bcrypt.hashpw(pw.encode('utf-8'), bcrypt.gensalt(12)).decode('utf-8')

def setup_users():
    print('[*] Setting up app_users table in Supabase...')
    
    ddl_sql = """
    CREATE TABLE IF NOT EXISTS public.app_users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email TEXT UNIQUE NOT NULL,
        password_hash TEXT NOT NULL,
        full_name TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'COMMERCIAL',
        is_active BOOLEAN DEFAULT TRUE,
        last_login TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
    );

    CREATE INDEX IF NOT EXISTS idx_app_users_email ON public.app_users(email);

    ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Public all access on app_users" ON public.app_users;
    CREATE POLICY "Public all access on app_users" ON public.app_users FOR ALL USING (true) WITH CHECK (true);
    """

    res = client.post(
        f'https://api.supabase.com/v1/projects/{PROJECT_REF}/database/query',
        headers={'Authorization': f'Bearer {SUPABASE_PAT}'},
        json={'query': ddl_sql}
    )
    print(f'[✓] DDL Migration status: {res.status_code}')

    headers = {
        'apikey': SUPABASE_KEY,
        'Authorization': f'Bearer {SUPABASE_KEY}',
        'Content-Type': 'application/json',
        'Prefer': 'return=representation,resolution=merge-duplicates'
    }

    admin_hash = hash_pw('Admin2026!*')
    commercial_hash = hash_pw('Ventas2026!*')

    initial_users = [
        {
            'email': 'admin@kbeautyhub.com',
            'password_hash': admin_hash,
            'full_name': 'Camilo Ortiz (Super Admin)',
            'role': 'ADMIN',
            'is_active': True
        },
        {
            'email': 'ventas@kbeautyhub.com',
            'password_hash': commercial_hash,
            'full_name': 'Equipo Comercial B2B',
            'role': 'COMMERCIAL',
            'is_active': True
        }
    ]

    post_res = client.post(f'{SUPABASE_URL}/rest/v1/app_users', headers=headers, json=initial_users)
    print(f'[✓] Seeded initial users: {post_res.status_code} -> {post_res.text}')

if __name__ == '__main__':
    setup_users()
