import os
import json
import httpx
from dotenv import load_dotenv

load_dotenv()

SUPABASE_URL = os.getenv('SUPABASE_URL', 'https://rykfqebqdvunwxqkheex.supabase.co').rstrip('/')
SUPABASE_KEY = os.getenv('SUPABASE_KEY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5a2ZxZWJxZHZ1bnd4cWtoZWV4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4ODIyOTg1OSwiZXhwIjoyMTAzODA1ODU5fQ.NCpBUHYAUSME_EjCeo6hyNGv4LkpLg9B6XCqY4LkYBM')
SUPABASE_PAT = os.getenv('SUPABASE_PAT', 'sbp_ee207100cbe762916e60181d68fc47f452633ab2')
PROJECT_REF = 'rykfqebqdvunwxqkheex'

client = httpx.Client(timeout=30.0)

def migrate_settings():
    print('[*] Creating platform_settings table in Supabase...')
    
    ddl_sql = """
    CREATE TABLE IF NOT EXISTS public.platform_settings (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category TEXT NOT NULL,
        config_key TEXT UNIQUE NOT NULL,
        config_value JSONB NOT NULL,
        description TEXT,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
    );

    CREATE INDEX IF NOT EXISTS idx_platform_settings_key ON public.platform_settings(config_key);

    ALTER TABLE public.platform_settings ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Public all access on platform_settings" ON public.platform_settings;
    CREATE POLICY "Public all access on platform_settings" ON public.platform_settings FOR ALL USING (true) WITH CHECK (true);
    """
    
    res = client.post(
        f'https://api.supabase.com/v1/projects/{PROJECT_REF}/database/query',
        headers={'Authorization': f'Bearer {SUPABASE_PAT}'},
        json={'query': ddl_sql}
    )
    print(f'[✓] Migration status: {res.status_code}')

    # Seed default platform settings
    headers = {
        'apikey': SUPABASE_KEY,
        'Authorization': f'Bearer {SUPABASE_KEY}',
        'Content-Type': 'application/json',
        'Prefer': 'return=representation,resolution=merge-duplicates'
    }

    default_settings = [
        {
            'category': 'COMMERCIAL',
            'config_key': 'currency_and_pricing',
            'config_value': {
                'primary_currency': 'USD',
                'secondary_currency': 'ARS',
                'exchange_rate': 1250.0,
                'default_wholesale_margin_pct': 44.2,
                'default_cost_markup_pct': 70.5,
                'default_moq': 3,
                'allow_custom_discounts': True
            },
            'description': 'Monedas, tipo de cambio y márgenes comerciales predeterminados.'
        },
        {
            'category': 'PURCHASING',
            'config_key': 'purchasing_criteria',
            'config_value': {
                'low_stock_threshold': 20,
                'critical_stock_threshold': 5,
                'international_freight_pct': 8.5,
                'customs_duty_pct': 12.0,
                'auto_create_po_draft': True
            },
            'description': 'Criterios de compra, umbrales de alerta de stock y costos de importación.'
        },
        {
            'category': 'TAXES',
            'config_key': 'tax_perceptions',
            'config_value': {
                'standard_vat_rate': 21.0,
                'reduced_vat_rate': 10.5,
                'gross_income_perception_rate': 3.5,
                'enable_tax_on_quotations': True,
                'company_legal_name': 'K-Beauty Group S.R.L.',
                'company_tax_id': '30-71689234-9'
            },
            'description': 'Alícuotas de IVA, percepciones fiscales y datos legales para cotizaciones.'
        },
        {
            'category': 'INTEGRATIONS',
            'config_key': 'api_sync_channels',
            'config_value': {
                'shopify': {
                    'enabled': False,
                    'store_url': 'kbeauty-demo.myshopify.com',
                    'api_version': '2024-01',
                    'sync_stock': True,
                    'sync_price': True,
                    'last_sync': None
                },
                'tiendanube': {
                    'enabled': False,
                    'store_id': '1092834',
                    'sync_stock': True,
                    'sync_price': False,
                    'last_sync': None
                },
                'mercadolibre': {
                    'enabled': False,
                    'app_id': 'MLA-9823412',
                    'sync_stock': True,
                    'last_sync': None
                }
            },
            'description': 'Conectores y credenciales para sincronización con Shopify, Tienda Nube y Mercado Libre.'
        }
    ]

    post_res = client.post(f'{SUPABASE_URL}/rest/v1/platform_settings', headers=headers, json=default_settings)
    print(f'[✓] Seeded default platform settings: {post_res.status_code}')

if __name__ == '__main__':
    migrate_settings()
