-- ==============================================================================
-- SUPABASE POSTGRESQL MIGRATION SCHEMA
-- Catálogo B2B / B2C - Productos, Marcas, Medidas, Imágenes y Rótulos
-- ==============================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. TABLA: BRANDS (Marcas)
CREATE TABLE IF NOT EXISTS public.brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    type TEXT DEFAULT 'B2B',
    priority TEXT DEFAULT 'Media',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. TABLA: PRODUCTS (Productos Principales)
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    ean TEXT,
    brand_id BIGINT REFERENCES public.brands(id) ON DELETE SET NULL,
    priority TEXT DEFAULT 'BAJA',
    format TEXT,
    description_short TEXT,
    description_full TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. TABLA: PRODUCT_DIMENSIONS (Medidas y Peso)
CREATE TABLE IF NOT EXISTS public.product_dimensions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL UNIQUE REFERENCES public.products(id) ON DELETE CASCADE,
    sku TEXT NOT NULL REFERENCES public.products(sku) ON DELETE CASCADE ON UPDATE CASCADE,
    height_cm NUMERIC(10, 2),
    width_cm NUMERIC(10, 2),
    depth_cm NUMERIC(10, 2),
    weight_raw TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 4. TABLA: PRODUCT_IMAGES (Galería de Fotos)
CREATE TABLE IF NOT EXISTS public.product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    sku TEXT NOT NULL REFERENCES public.products(sku) ON DELETE CASCADE ON UPDATE CASCADE,
    image_url TEXT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 1,
    is_primary BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 5. TABLA: PRODUCT_LABELS (Rótulos y Documentación)
CREATE TABLE IF NOT EXISTS public.product_labels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    sku TEXT NOT NULL REFERENCES public.products(sku) ON DELETE CASCADE ON UPDATE CASCADE,
    ean TEXT,
    label_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- INDEXES FOR MAXIMUM QUERY PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_products_sku ON public.products(sku);
CREATE INDEX IF NOT EXISTS idx_products_ean ON public.products(ean);
CREATE INDEX IF NOT EXISTS idx_products_brand_id ON public.products(brand_id);
CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON public.product_images(product_id);
CREATE INDEX IF NOT EXISTS idx_product_images_sku ON public.product_images(sku);
CREATE INDEX IF NOT EXISTS idx_product_dimensions_product_id ON public.product_dimensions(product_id);
CREATE INDEX IF NOT EXISTS idx_product_labels_product_id ON public.product_labels(product_id);

-- TRIGGER FUNCTION FOR UPDATED_AT
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ATTACH TRIGGERS
DROP TRIGGER IF EXISTS set_brands_updated_at ON public.brands;
CREATE TRIGGER set_brands_updated_at
    BEFORE UPDATE ON public.brands
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_products_updated_at ON public.products;
CREATE TRIGGER set_products_updated_at
    BEFORE UPDATE ON public.products
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_product_dimensions_updated_at ON public.product_dimensions;
CREATE TRIGGER set_product_dimensions_updated_at
    BEFORE UPDATE ON public.product_dimensions
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_dimensions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_labels ENABLE ROW LEVEL SECURITY;

-- Allow public read access (anon / authenticated)
CREATE POLICY "Allow public read on brands" ON public.brands FOR SELECT USING (true);
CREATE POLICY "Allow public read on products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Allow public read on product_dimensions" ON public.product_dimensions FOR SELECT USING (true);
CREATE POLICY "Allow public read on product_images" ON public.product_images FOR SELECT USING (true);
CREATE POLICY "Allow public read on product_labels" ON public.product_labels FOR SELECT USING (true);
