-- ==============================================================================
-- SUPABASE POSTGRESQL ENTERPRISE MASTER SCHEMA
-- Catálogo Maestro, Abastecimiento B2B, Cotizaciones & Trazabilidad Multicanal
-- ==============================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. TABLA: BRANDS (Marcas & Proveedores)
CREATE TABLE IF NOT EXISTS public.brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    website TEXT,
    status TEXT DEFAULT 'ACTIVE', -- 'RADAR', 'PROSPECT', 'NEGOTIATING', 'ACTIVE'
    type TEXT DEFAULT 'B2B',
    priority TEXT DEFAULT 'Media',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. TABLA: BRAND_SOURCES (Fuentes Oficiales D2C)
CREATE TABLE IF NOT EXISTS public.brand_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT REFERENCES public.brands(id) ON DELETE CASCADE,
    brand_name TEXT NOT NULL,
    url TEXT NOT NULL UNIQUE,
    source_type TEXT DEFAULT 'SHOPIFY_API',
    crawl_status TEXT DEFAULT 'PENDING',
    last_crawled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. TABLA: PRODUCTS (Catálogo Maestro B2B/B2C)
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    ean TEXT,
    brand_id BIGINT REFERENCES public.brands(id) ON DELETE SET NULL,
    priority TEXT DEFAULT 'MEDIA',
    format TEXT,
    category TEXT DEFAULT 'Cuidado Facial',
    description_short TEXT,
    description_full TEXT,
    key_ingredients TEXT,
    usage_instructions TEXT,
    skin_types TEXT,
    benefits TEXT,
    url_origen TEXT,
    ruta_tecnica TEXT DEFAULT 'RUTA_TEXTO',
    lifecycle_stage TEXT DEFAULT 'CATALOGING', -- 'DISCOVERY', 'PURCHASE', 'CATALOGING', 'AI_ENRICHMENT', 'APPROVAL', 'READY_TO_PUBLISH', 'PUBLISHED'
    verification_status TEXT DEFAULT 'VERIFICADO_OFICIAL',
    completeness_score INTEGER DEFAULT 100,
    rejection_reason TEXT,
    -- Commercial & Wholesale B2B fields
    wholesale_price NUMERIC(10, 2) DEFAULT 14.50,
    retail_price NUMERIC(10, 2) DEFAULT 26.00,
    cost_price NUMERIC(10, 2) DEFAULT 8.50,
    moq INTEGER DEFAULT 3,
    stock_quantity INTEGER DEFAULT 100,
    is_b2b_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 4. TABLA: PRODUCT_DIMENSIONS (Medidas y Peso)
CREATE TABLE IF NOT EXISTS public.product_dimensions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL UNIQUE REFERENCES public.products(id) ON DELETE CASCADE,
    sku TEXT NOT NULL REFERENCES public.products(sku) ON DELETE CASCADE ON UPDATE CASCADE,
    height_cm NUMERIC(10, 2),
    width_cm NUMERIC(10, 2),
    depth_cm NUMERIC(10, 2),
    weight_raw TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 5. TABLA: PRODUCT_IMAGES (Galería de Fotos Oficiales)
CREATE TABLE IF NOT EXISTS public.product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    sku TEXT REFERENCES public.products(sku) ON DELETE CASCADE ON UPDATE CASCADE,
    image_url TEXT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 1,
    is_primary BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT uq_product_image UNIQUE (product_id, image_url)
);

-- 6. TABLA: PRODUCT_LABELS (Rótulos y Documentación Oficial)
CREATE TABLE IF NOT EXISTS public.product_labels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    sku TEXT REFERENCES public.products(sku) ON DELETE CASCADE ON UPDATE CASCADE,
    ean TEXT,
    label_url TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT uq_product_label UNIQUE (product_id, label_url)
);

-- 7. TABLA: DISCOVERED_PRODUCTS (Scraping & Discovery D2C)
CREATE TABLE IF NOT EXISTS public.discovered_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT REFERENCES public.brands(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    sku TEXT,
    ean TEXT,
    format TEXT,
    image_url TEXT,
    external_url TEXT,
    price_raw TEXT,
    raw_data JSONB DEFAULT '{}'::jsonb,
    status TEXT DEFAULT 'DISCOVERED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 8. TABLA: NEGOTIATIONS (Negociaciones Comerciales B2B)
CREATE TABLE IF NOT EXISTS public.negotiations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT NOT NULL REFERENCES public.brands(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    status TEXT DEFAULT 'PROSPECTION', -- 'PROSPECTION', 'CONTACTED', 'NEGOTIATING', 'AGREEMENT', 'CLOSED', 'REJECTED'
    contact_name TEXT,
    contact_email TEXT,
    contact_phone TEXT,
    notes TEXT,
    agreement_terms JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 9. TABLA: PURCHASE_ORDERS (Órdenes de Compra Internacional)
CREATE TABLE IF NOT EXISTS public.purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_number TEXT UNIQUE NOT NULL,
    brand_id BIGINT NOT NULL REFERENCES public.brands(id) ON DELETE RESTRICT,
    status TEXT DEFAULT 'DRAFT', -- 'DRAFT', 'CONFIRMED', 'IN_TRANSIT', 'RECEIVED', 'CANCELLED'
    total_amount_usd NUMERIC(12, 2) DEFAULT 0,
    items_count INTEGER DEFAULT 0,
    notes TEXT,
    expected_delivery_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 10. TABLA: PURCHASE_ORDER_ITEMS (Detalle de OC)
CREATE TABLE IF NOT EXISTS public.purchase_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id BIGINT NOT NULL REFERENCES public.purchase_orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    sku TEXT,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_cost_usd NUMERIC(10, 2) NOT NULL DEFAULT 0,
    subtotal_usd NUMERIC(12, 2) NOT NULL DEFAULT 0
);

-- 11. TABLA: PRODUCT_CHANNELS (Matriz de Publicación Multicanal)
CREATE TABLE IF NOT EXISTS public.product_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    channel_name TEXT NOT NULL, -- 'shopify', 'tiendanube', 'mercadolibre'
    published_status TEXT DEFAULT 'PENDING', -- 'PENDING', 'ACTIVE', 'ERROR', 'PAUSED'
    channel_sku TEXT,
    sale_price NUMERIC(10, 2),
    last_sync_at TIMESTAMPTZ,
    sync_errors TEXT,
    CONSTRAINT uq_product_channel UNIQUE (product_id, channel_name)
);

-- 12. TABLA: B2B_CLIENTS (Directorio de Clientes Mayoristas)
CREATE TABLE IF NOT EXISTS public.b2b_clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    tax_id TEXT,
    contact_name TEXT,
    email TEXT,
    phone TEXT,
    address TEXT,
    city TEXT,
    country TEXT DEFAULT 'Argentina',
    price_tier TEXT DEFAULT 'MAYORISTA_ESTANDAR',
    discount_rate NUMERIC(5, 2) DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 13. TABLA: B2B_ORDERS (Pedidos y Cotizaciones Mayoristas)
CREATE TABLE IF NOT EXISTS public.b2b_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number TEXT UNIQUE NOT NULL,
    client_id BIGINT REFERENCES public.b2b_clients(id) ON DELETE SET NULL,
    client_name TEXT NOT NULL,
    client_tax_id TEXT,
    client_email TEXT,
    client_phone TEXT,
    status TEXT DEFAULT 'QUOTED', -- 'QUOTED', 'CONFIRMED', 'PREPARING', 'DELIVERED', 'CANCELLED'
    currency TEXT DEFAULT 'USD',
    subtotal NUMERIC(12, 2) DEFAULT 0,
    discount_amount NUMERIC(12, 2) DEFAULT 0,
    tax_amount NUMERIC(12, 2) DEFAULT 0,
    shipping_amount NUMERIC(12, 2) DEFAULT 0,
    total_amount NUMERIC(12, 2) DEFAULT 0,
    payment_terms TEXT DEFAULT 'Transferencia Bancaria Anticipada',
    validity_days INTEGER DEFAULT 15,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 14. TABLA: B2B_ORDER_ITEMS (Ítems de Pedidos Mayoristas)
CREATE TABLE IF NOT EXISTS public.b2b_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES public.b2b_orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    sku TEXT,
    ean TEXT,
    product_name TEXT NOT NULL,
    brand_name TEXT,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(10, 2) NOT NULL DEFAULT 0,
    discount_percent NUMERIC(5, 2) DEFAULT 0,
    subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0
);

-- 15. TABLA: ACTIVITY_LOG (Auditoría & Trazabilidad Inmutable)
CREATE TABLE IF NOT EXISTS public.activity_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor TEXT NOT NULL,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 16. TABLA: AI_RUNS (Registro de Ejecuciones de Agentes IA)
CREATE TABLE IF NOT EXISTS public.ai_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_name TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT,
    prompt_summary TEXT,
    model_used TEXT DEFAULT 'gemini-3.6-flash',
    status TEXT DEFAULT 'COMPLETED',
    result_data JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- ==============================================================================
-- INDEXES FOR OPTIMAL PERFORMANCE
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_products_sku ON public.products(sku);
CREATE INDEX IF NOT EXISTS idx_products_ean ON public.products(ean);
CREATE INDEX IF NOT EXISTS idx_products_brand_id ON public.products(brand_id);
CREATE INDEX IF NOT EXISTS idx_products_stage ON public.products(lifecycle_stage);
CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON public.product_images(product_id);
CREATE INDEX IF NOT EXISTS idx_product_images_sku ON public.product_images(sku);
CREATE INDEX IF NOT EXISTS idx_product_dimensions_product_id ON public.product_dimensions(product_id);
CREATE INDEX IF NOT EXISTS idx_product_labels_product_id ON public.product_labels(product_id);
CREATE INDEX IF NOT EXISTS idx_discovered_products_brand ON public.discovered_products(brand_id);
CREATE INDEX IF NOT EXISTS idx_negotiations_brand ON public.negotiations(brand_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_number ON public.purchase_orders(po_number);
CREATE INDEX IF NOT EXISTS idx_b2b_clients_company ON public.b2b_clients(company_name);
CREATE INDEX IF NOT EXISTS idx_b2b_clients_tax_id ON public.b2b_clients(tax_id);
CREATE INDEX IF NOT EXISTS idx_b2b_orders_number ON public.b2b_orders(order_number);
CREATE INDEX IF NOT EXISTS idx_b2b_orders_client_id ON public.b2b_orders(client_id);
CREATE INDEX IF NOT EXISTS idx_b2b_order_items_order ON public.b2b_order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_activity_log_created_at ON public.activity_log(created_at DESC);

-- ==============================================================================
-- TRIGGERS PARA UPDATED_AT AUTOMÁTICO
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_brands_updated_at ON public.brands;
CREATE TRIGGER set_brands_updated_at BEFORE UPDATE ON public.brands FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_products_updated_at ON public.products;
CREATE TRIGGER set_products_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_b2b_clients_updated_at ON public.b2b_clients;
CREATE TRIGGER set_b2b_clients_updated_at BEFORE UPDATE ON public.b2b_clients FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_b2b_orders_updated_at ON public.b2b_orders;
CREATE TRIGGER set_b2b_orders_updated_at BEFORE UPDATE ON public.b2b_orders FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brand_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_dimensions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_labels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discovered_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.negotiations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.b2b_clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.b2b_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.b2b_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_runs ENABLE ROW LEVEL SECURITY;

-- Allow read and write access for authenticated application operations
CREATE POLICY "Public read on brands" ON public.brands FOR SELECT USING (true);
CREATE POLICY "Public write on brands" ON public.brands FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Public all on products" ON public.products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public all on product_dimensions" ON public.product_dimensions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public all on product_images" ON public.product_images FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public all on product_labels" ON public.product_labels FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public all on brand_sources" ON public.brand_sources FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public all on discovered_products" ON public.discovered_products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public all on negotiations" ON public.negotiations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public all on purchase_orders" ON public.purchase_orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public all on purchase_order_items" ON public.purchase_order_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public all on product_channels" ON public.product_channels FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public all on b2b_clients" ON public.b2b_clients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public all on b2b_orders" ON public.b2b_orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public all on b2b_order_items" ON public.b2b_order_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public all on activity_log" ON public.activity_log FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public all on ai_runs" ON public.ai_runs FOR ALL USING (true) WITH CHECK (true);

