-- 1. INSERT BRANDS (74 Marcas Maestras Normalizadas)
INSERT INTO public.brands (id, name, type, priority) VALUES (1, 'A BY UNLEASHIA', 'B2B', 'Secundario') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (2, 'ABIB', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (3, 'AGE-R', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (4, 'ANUA', 'B2B', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (5, 'APLB', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (6, 'ARENCIA', 'B2B', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (7, 'AROMATICA', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (8, 'AXIS-Y', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (9, 'BAREN', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (10, 'BBLAB', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (11, 'BEAUTY OF JOSEON', 'B2B', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (12, 'BEK', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (13, 'BIODANCE', 'B2B', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (14, 'BIOHEAL BOH', 'B2C', 'Secundario') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (15, 'BRINGGREEN', 'B2C', 'Secundario') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (16, 'CELIMAX', 'B2B', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (17, 'CENTELLIAN24', 'B2B', 'Secundario') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (18, 'COMMONLABS', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (19, 'COONY', 'B2C', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (20, 'COSRX', 'B2B', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (21, 'DAILY COMMA', 'B2B', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (22, 'DEAR A', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (23, 'DR.ALTHEA', 'B2B', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (24, 'DR.MELAXIN', 'B2B', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (25, 'ELIZA', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (26, 'ELROEL', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (27, 'EQQUALBERRY', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (28, 'ESTHER FORMULA', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (29, 'FILLIMILLI', 'B2C', 'Secundario') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (30, 'FOODOLOGY', 'B2B', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (31, 'FRANKLY', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (32, 'FULLY', 'B2C', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (33, 'FURRIKY', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (34, 'FWEE', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (35, 'GLOW', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (36, 'GROWUS', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (37, 'HARUHARU WONDER', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (38, 'HEIMISH', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (39, 'HEVEBLUE', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (40, 'IUNIK', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (41, 'JUMISO', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (42, 'K-SECRET', 'B2B', 'Secundario') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (43, 'KAHI', 'B2C', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (44, 'KONJAC', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (45, 'KUNDAL', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (46, 'LILYEVE', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (47, 'MADECA 21', 'B2B', 'Secundario') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (48, 'MANYO', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (49, 'MARY&MAY', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (50, 'MEDICUBE', 'B2B', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (51, 'MEDIPEEL', 'B2B', 'Secundario') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (52, 'MEDITHERAPY', 'B2B', 'Secundario') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (53, 'MENOKIN', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (54, 'MIXSOON', 'B2B', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (55, 'MOEV', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (56, 'NUMBUZIN', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (57, 'OBGE', 'B2C', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (58, 'PERIPERA', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (59, 'PRELUDE', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (60, 'PURITO', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (61, 'PYUNKANG', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (62, 'REJU-AL', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (63, 'ROUND LAB', 'B2B', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (64, 'SEAPURI', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (65, 'SKIN1004', 'B2B', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (66, 'SKYBOTTLE', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (67, 'SOME BY MI', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (68, 'SUNGBOON', 'B2B', 'Media') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (69, 'TIRTIR', 'B2B', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (70, 'TOCOBO', 'B2B', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (71, 'TORRIDEN', 'B2B', 'Secundario') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (72, 'UNLEASHIA', 'B2B', 'Secundario') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (73, 'VT COSMETICS', 'B2B', 'Urgente') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
INSERT INTO public.brands (id, name, type, priority) VALUES (74, 'WAKEMAKE', 'B2C', 'Secundario') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, priority = EXCLUDED.priority;
SELECT setval('public.brands_id_seq', 74, true);
